### ISSUE TITLE
Resources getting back to default for system.slice and user.slice for Cgroup v2

### ISSUE THREAD

**Issue by Apurva1995** [libcgroup/libcgroup#28]
We are using cgconfigparser utility for setting the resource of system.slice and user.slice for cpu and memory controller. It is able to set the resources, but it's getting reverted after few seconds. Is it the expected behavior?

E.g. cgconfig.conf file
group system.slice {
                memory {
                   memory.max="20G";
        }
}

OS : SLES15 SP2
Hierarchy : unified(Pure V2)

**Comment by Werkov** [comment]
Hello @Apurva1995. Both `system.slice` and `user.slice` cgroups are managed by systemd and systemd and cgconfigparser are stumbling over each other. Such a scenario [is not supported by systemd](https://systemd.io/CGROUP_DELEGATION/#three-scenarios).

I wonder what is the reason you prefer configuration via cgconfig.conf instead of systemd unit files in this case? Is there anything more besides memory limits?

**Comment by drakenclimber** [comment]
@Werkov is correct.  On cgroup v2 systems, systemd and libcgroup have strict rules on how to have them work together.  While officially unsupported, cgroup v1 is much more tolerant of nonstandard configurations.

Long term I plan to make libcgroup work more closely with systemd, but that is still a ways out.

**Comment by Apurva1995** [comment]
Thanks @Werkov @drakenclimber . I got the point. The recommended way is using the unit files in this case.

**Comment by drakenclimber** [comment]
There is work to do here to improve the interaction between systemd and libcgroup, but I don't think this issue is the right place to track such work.

I'm going to close this, but feel free to add comments or reopen if you have additional thoughts to add.
