### ISSUE TITLE
Incorrect systemd.h inclusion if systemd feature is disabled

### ISSUE THREAD

**Issue by lucasdietrich** [libcgroup/libcgroup#413]
File [include/Makefile.am](https://github.com/libcgroup/libcgroup/blob/5d07f1a3b213d6d27d4cca65de5fe035898233d3/include/Makefile.am#L7-L9) conditionally instructs to not install systemd.h header depending on _systemd_ feature, however header [include/libcgroup.h](https://github.com/libcgroup/libcgroup/blob/5d07f1a3b213d6d27d4cca65de5fe035898233d3/include/libcgroup.h#L21) unconditionally includes this previous header.

I'm compiling this library in the context of a Yocto environement, if I build libcgroup with `--enable-systemd=no`, _systemd.h_ header is not installed in the development package, when including `<libcgroup.h>` from a C project this causes a gcc error saying it cannot find `systemd.h` header 

Moving `libcgroup/systemd.h` to `nobase_include_HEADERS` in `include/Makefile.am` solves our issue:

```
# Using 'nobase_', we what groups.h in /usr/include/libcgroup/ directory
nobase_include_HEADERS = libcgroup.h libcgroup/error.h libcgroup/init.h \
			 libcgroup/groups.h libcgroup/tasks.h \
			 libcgroup/iterators.h libcgroup/config.h \
			 libcgroup/log.h libcgroup/tools.h \
			 libcgroup/systemd.h
```

Is this a indented ? I can elaborate a patch

**Comment by ColdForest** [comment]
I just ran into this as well.

**Comment by kamalesh-babulal** [comment]
@lucasdietrich @ColdForest Thanks for the report.  I guess moving `libcgroup/systemd.h` out of `#ifdef WITH_SYSTEMD` into `nobase_` will be a partial fix if `libcgroup/systemd.h` is to be included unconditionally in the `include/Makefile.am`. Additionally,  it would require `WITH_SYSTEMD=n` version of functions included from `libcgroup/systemd.h` for graceful errors, instead of build failures.  The function would return an error message, along with `ECGROUPNOTCOMPILED?` as the return value.

Another approach would be to use `#ifdef WITH_SYSTEMD` while adding `libcgroup/systemd.h` in `libcgroup.h` but that would require moving out the `systemd` configuration parser functions to out of `libcgroup/systemd.h`, but that doesn't sound like a great option.

**Comment by Sangeetha-E** [comment]
I'm encountering the same issue as well. Here is the log:
```
# gcc -o get_mount_point get_mount_point.c -lcgroup
In file included from get_mount_point.c:2:0:
/usr/include/libcgroup.h:22:31: fatal error: libcgroup/systemd.h: No such file or directory
 #include <libcgroup/systemd.h>
                               ^
compilation terminated.
#
```
Is there any available fix for this?

**Comment by kamalesh-babulal** [comment]
@lucasdietrich @ColdForest @Sangeetha-E Can you please give #414 a try?

**Comment by lucasdietrich** [comment]
I just tested your changes in my Yocto project, and everything compiled without error. The issue seems to be resolved on my side, thank you !

Steps:
1. Building libcgroup development package with your changes
2. Building my application linked against the compiled library

**Comment by lucasdietrich** [comment]
Sure `Reported-by: Lucas Dietrich <lucas.dietrich@socomec.com>`

**Comment by kamalesh-babulal** [comment]
#414 resolves the reported issue, closing it.
